### ISSUE TITLE
Отрицательный uint в QueueFamilyInfo 

### ISSUE THREAD

**Issue by 1vanK** [darkoffalex/vulkan#1]
https://github.com/darkoffalex/vulkan/blob/master/Sources/VkToolkit.h

```
struct QueueFamilyInfo {

	// Индексты семейств очередей
	uint32_t graphics = -1;
	uint32_t present = -1;
	uint32_t compute = -1;
	uint32_t transfer = -1;

	// Совместим ли набор доступных семейств с рендерингом
	bool IsRenderingCompatible() const {
		return graphics >= 0 && present >= 0;
	}
};
```

У тебя всегда выполняется условие graphics >= 0 && present >= 0, так как uint32_t всегда >=0 (там переполнение при отрицательных числах)

**Comment by darkoffalex** [comment]
И правда. Пофиксил в коммите 54e8636bceb75064636b6ca5fc26ad6ac3edeae
