### ISSUE TITLE
GetAsyncKeyState использование для проверки состояния нажатия

### ISSUE THREAD

**Issue by MikhailGorobets** [darkoffalex/vulkan#2]
Используй лучше функцию. 
#define KEYDOWN(vk_code)  ((GetAsyncKeyState(vk_code) & 0x8000) ? 1 : 0)
#define KEYUP(vk_code)         ((GetAsyncKeyState(vk_code) & 0x8000) ? 0 : 1)

Так в любое момент можешь узнать состояние независимо от цикла событий окна

**Comment by Redee** [comment]
При этом проверяем все клавиши в начале кадра.

`const int count = 255;
bool keys[count]{};
bool* pt = keys;
for (int n = 0; n < count; n++, pt++)
	*pt = GetAsyncKeyState(n);`

**Comment by Redee** [comment]
При этом проверяем все клавиши в начале кадра.
```
const int count = 255;
bool keys[count]{};
bool* pt = keys;
for (int n = 0; n < count; n++, pt++)
	*pt = GetAsyncKeyState(n);

**Comment by MikhailGorobets** [comment]
Ок. Плохо чекнул. Лучше SDL юзать

**Comment by Redee** [comment]
Кому что... мне лучше свое )).
А так да и SDL, и GLFW, и всякие другие либы имеются...

**Comment by darkoffalex** [comment]
Применил данный подход в комите 48a2775bb0e3f6226445d63052d20dfbaeb6496c
Вроде всё работает нормально
